on: [push]

jobs:  
  my-job:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with: 
          myInput: 'Cha C'
    - name: output
        run:  |
          echo ${{ steps.hello.outputs.memory  }}
          echo "Total memory successfuly output"
